# Generated by Django 4.2.6 on 2024-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='presentation',
            field=models.CharField(max_length=210),
        ),
    ]
